# This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.

name: Chaise e2e test

on: 
  push:
    branches: 
      - 'master'
      - 'github-workflow-setup'

jobs:
  install-and-test:
    runs-on: ubuntu-16.04

    steps:
      - name: setup-system
        run: |
          export TZ=America/Los_Angeles
          export PATH="$(systemd-path user-binaries):$PATH"
      - name: setup-postgresql-10
        run: |
          sudo apt-get -y purge postgresql-9.1 postgresql-9.2 postgresql-9.3 postgresql-9.4 postgresql-9.5 postgresql-9.6 || true
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main" > /etc/apt/sources.list.d/PostgreSQL.list'
          sudo apt-get -y update
          sudo apt-get install postgresql-10
          sudo service postgresql start 10
      - name: setup-apache
        run: |
          sudo apt-get install apache2 apache2-dev ssl-cert libapache2-mod-wsgi-py3
          sudo ln -s /etc/apache2/conf-enabled /etc/apache2/conf.d
          sudo a2enmod ssl
          sudo a2ensite default-ssl
          sudo groupadd -o -g $(id -g www-data) apache 
      - name: Checkout repository code
        uses: actions/checkout@v2
